In [ ]:
#  마방진(가로, 세로, 대각선 방향의 숫자 합계가 모두 같은 배열) 만들기
# 최초의 1이 채워지는 자리는 첫 줄 정 가운데 열이다. -> 홀수차 정방행렬(행과 열의 개수가 같은 행렬)만 가능하다.
# 직전에 채워진 숫자 값에 따라서 다음에 채워질 숫자의 위치가 결정된다.
# 직전에 채워진 숫자가 행렬의 차수(n)의 배수면 다음 숫자는 아래줄에 채운다. -> 행 + 1
# 직전에 채워진 숫자가 n의 배수가 아니면 다음 숫자는 오른쪽 위 방향으로 채운다. -> 행 - 1, 열 + 1
# 행이 0보다 작아지면 행의 위치를 마지막 위치로 변경한 행과 열이 행렬의 차수와 같아지면 열의 위치를 0으로 변경한다.

In [5]:
# 1차원 리스트 만들기
a = [0 for i in range(5)] # 0이 5번 반복되는 1차원 리스트
print(a)
# 2차원 리스트 만들기 -> 리스트이름 = [[0] * 열의개수 for 변수 in range(행의개수)]
a = [[0] * 5 for i in range(5)]
print(a)
import numpy as np
b = np.array(a)
print(b)

[0, 0, 0, 0, 0]
[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [10]:
for i in range(5):
    for j in range(5):
        print('{0:2d} '.format(a[i][j]), end='')
    print()

 0  0  0  0  0 
 0  0  0  0  0 
 0  0  0  0  0 
 0  0  0  0  0 
 0  0  0  0  0 


In [12]:
# 5행 5열의 2차원 리스트를 선언한다.
a = [[0] * 5 for i in range(5)]
# 5행 5열일 경우 최초의 1이 채워질 위치를 정한다.
i = 0
j = 2

# 마방진에 채워질 숫자의 개수만큼 반복하며 2차원 리스트에 숫자를 채워준다.
for k in range(1, 26):
    a[i][j] = k
    # 마방진에 채운 숫자가 5의 배수인가 판단한다.
    if k % 5 == 0:
        # 5의 배수면 다음에 채워질 숫자의 위치는 행만 1 증가시킨디ㅏ.
        i += 1
    else:
        # 5의 배수가 아니면 다음에 채워질 숫자의 위치는 행은 1감소, 열은 1 증가시킨다.
        i -= 1
        # 행이 감소하다가 0보다 작아지면 마지막 행으로 열의 위치를 조정한다.
        if i < 0:
            i = 4
        j += 1
        # 열이 증가하다가 5가 되면 첫 번째 열로 열의 위치를 조정한다.
        if j >= 5:
            j = 0
            
for i in range(5): # 행
    for j in range(5): # 열
        print('{0:2d} '.format(a[i][j]), end='')
    print()

17 24  1  8 15 
23  5  7 14 16 
 4  6 13 20 22 
10 12 19 21  3 
11 18 25  2  9 


In [26]:
# 작성할 마방진의 차수를 3이상인 홀수로 입력받는다.
while True: 
    number = int(input('3 이상의 홀수를 입력해주세요 : '))
    if number >= 3 and number % 2 == 1:
        break
    print('다시 입력해주세요')

a = [[0] * number for i in range(number)]
i = 0
# 행렬의 차수에 따라 최초의 1이 채워질 열을 계산한다.
j = number // 2

# 마방진에 채워질 숫자의 개수만큼 반복하며 2차원 리스트에 숫자를 채워준다.
for k in range(1, number*number+1):
    a[i][j] = k
    # 마방진에 채운 숫자가 5의 배수인가 판단한다.
    if k % number == 0:
        # 5의 배수면 다음에 채워질 숫자의 위치는 행만 1 증가시킨디ㅏ.
        i += 1
    else:
        # 5의 배수가 아니면 다음에 채워질 숫자의 위치는 행은 1감소, 열은 1 증가시킨다.
        i -= 1
        # 행이 감소하다가 0보다 작아지면 마지막 행으로 열의 위치를 조정한다.
        if i < 0:
            i = number - 1
        j += 1
        # 열이 증가하다가 5가 되면 첫 번째 열로 열의 위치를 조정한다.
        if j >= number:
            j = 0
            
for i in range(number): # 행
    for j in range(number): # 열
        print('{0:3d} '.format(a[i][j]), end='')
    print()

3 이상의 홀수를 입력해주세요 : 13
 93 108 123 138 153 168   1  16  31  46  61  76  91 
107 122 137 152 167  13  15  30  45  60  75  90  92 
121 136 151 166  12  14  29  44  59  74  89 104 106 
135 150 165  11  26  28  43  58  73  88 103 105 120 
149 164  10  25  27  42  57  72  87 102 117 119 134 
163   9  24  39  41  56  71  86 101 116 118 133 148 
  8  23  38  40  55  70  85 100 115 130 132 147 162 
 22  37  52  54  69  84  99 114 129 131 146 161   7 
 36  51  53  68  83  98 113 128 143 145 160   6  21 
 50  65  67  82  97 112 127 142 144 159   5  20  35 
 64  66  81  96 111 126 141 156 158   4  19  34  49 
 78  80  95 110 125 140 155 157   3  18  33  48  63 
 79  94 109 124 139 154 169   2  17  32  47  62  77 
